<?php
/**
 * Prints the security headers as nginx `add_header` lines (deploy/nginx/security-headers.conf).
 *   php php_backend/scripts/print_security_headers.php > deploy/nginx/security-headers.conf
 */
define('TESTING_MODE', true);
putenv('JWT_SECRET=' . bin2hex(random_bytes(32)));   // config.php insists on a secret; none is used here
require_once __DIR__ . '/../config.php';

echo "# Generated by php_backend/scripts/print_security_headers.php from kuraSecurityHeaders() in config.php.\n";
echo "# Do not edit by hand: tests/test_nginx_deploy.php checks it is in sync.\n";
foreach (kuraSecurityHeaders() as $name => $value) {
    echo 'add_header ' . $name . ' "' . str_replace(['\\', '"'], ['\\\\', '\\"'], $value) . "\" always;\n";
}
